=== wanderingivan/socialnet-example/src/test/resources/test.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dataset (
	users*,
	friendships*,
	friend_requests*,
	wall_posts*,
	wall_messages*,
	chats*,
	chat_messages*,	
	chats_join_table*,
	images*,
	likes*,
    tasks*,
    authorities*
)>

<!ELEMENT users EMPTY>
<!ATTLIST users
	user_id CDATA #IMPLIED
	username CDATA #REQUIRED 
	email CDATA #REQUIRED
	password CDATA #REQUIRED
	profilePic CDATA #IMPLIED
	enabled CDATA #IMPLIED
>

<!ELEMENT friendships EMPTY>
<!ATTLIST friendships
	user1_id CDATA #REQUIRED
	user2_id CDATA #REQUIRED
	createdOn CDATA #IMPLIED
>

<!ELEMENT friend_requests EMPTY>
<!ATTLIST friend_requests 
	friend_request_id CDATA #IMPLIED
	accepted CDATA #REQUIRED
	denied CDATA #IMPLIED
	sender_id CDATA #REQUIRED
	receiver_id CDATA #REQUIRED
>
<!ELEMENT wall_posts EMPTY>
<!ATTLIST wall_posts
	wall_post_id CDATA #IMPLIED
	owner_id CDATA #REQUIRED
>
<!ELEMENT wall_messages EMPTY>
<!ATTLIST wall_messages
	wall_message_id CDATA #IMPLIED
	message CDATA #REQUIRED
	sender_id CDATA #REQUIRED
	wall_post_id CDATA #REQUIRED
>

<!ELEMENT chats_join_table EMPTY>
<!ATTLIST chats_join_table
	chat_id CDATA #REQUIRED
	user_id CDATA #REQUIRED
>

<!ELEMENT chat_messages EMPTY>
<!ATTLIST chat_messages
	message_id CDATA #IMPLIED
	message CDATA #REQUIRED
	sent CDATA #IMPLIED
	chat_id CDATA #REQUIRED
	sender_id CDATA #REQUIRED
>

<!ELEMENT chats EMPTY>
<!ATTLIST chats
	chat_id CDATA #IMPLIED
	lastUpdate CDATA #IMPLIED
>
<!ELEMENT images EMPTY>
<!ATTLIST images
    image_id CDATA #IMPLIED
    imagePath CDATA #REQUIRED
    user_id CDATA #IMPLIED
>
<!ELEMENT likes EMPTY>
<!ATTLIST likes 
	likes_id CDATA #IMPLIED
	sender_id CDATA #REQUIRED
	wall_post_id CDATA #REQUIRED
>

<!ELEMENT tasks EMPTY>
<!ATTLIST tasks
	task_id CDATA #IMPLIED
	name CDATA #REQUIRED
	description CDATA #REQUIRED
	assigner CDATA #REQUIRED
	assignee CDATA #REQUIRED
>

<!ELEMENT authorities EMPTY >
<!ATTLIST authorities
	username CDATA #REQUIRED
	authority  CDATA #REQUIRED 
>

=== wanderingivan/socialnet-example/src/test/resources/DbTestDataSet.xml
<!DOCTYPE dataset PUBLIC "//UNKNOWN/" "test.dtd">
<dataset>
	<users user_id="1" username="username1" email="some@email" password="Bar" profilePic="350x350News.png" enabled="1"/>
	<users user_id="2" username="username2" email="some@email1" password="" profilePic="News.png"  enabled="1"/>
	<users username="username3" email="some@email2" password="Bar" profilePic="News.png"  enabled="1"/>
	<users user_id="4" username="username4" email="some@email3" password="" profilePic="News.png"  enabled="1"/>
	<users user_id="5" username="username5" email="some@email4" profilePic="350x350News.png"   password="" enabled="1"/>
	<users user_id="6" username="username6" email="some@email5" profilePic="News.png"  password="" enabled="1"/>	
	<users user_id="7" username="username7" email="some@email6" password="" profilePic="350x350News.png"  enabled="0"/> 
	<users user_id="8" username="username8" email="some@email7" profilePic="News.png"  password="" enabled="1"/>
	<users user_id="9" username="username9" email="some@email8" password="" profilePic="50x350News.png"  enabled="1"/>
	<users user_id="10" username="username10" password="" email="some@email9" profilePic="350x350News.png"  enabled="1"/>
	<users user_id="11" username="username11" password="" email="some@email10" profilePic="350x350News.png"  enabled="1"/>
		
	<friendships user1_id="5" user2_id="1"/>
	<friendships user1_id="1" user2_id="5"/>
	<friendships user1_id="5" user2_id="6"/>
	<friendships user1_id="6" user2_id="5"/>
	<friendships user1_id="5" user2_id="7"/>
	<friendships user1_id="7" user2_id="5"/>
	<friendships user1_id="5" user2_id="8"/>
	<friendships user1_id="8" user2_id="5"/>
	<friendships user1_id="5" user2_id="9"/>
	<friendships user1_id="9" user2_id="5"/>
	<friendships user1_id="6" user2_id="7"/>
	<friendships user1_id="7" user2_id="6"/>
	<friend_requests sender_id="7" receiver_id="6" accepted="0" denied="0"/> 
	<friend_requests friend_request_id="1" sender_id="5" receiver_id="2" accepted="0" denied="0"/> 
	<wall_posts wall_post_id="3" owner_id="8"/>
	<wall_posts wall_post_id="4" owner_id="7"/>
	<wall_messages sender_id="9" wall_post_id="3" message="somemesage"/>
	<wall_messages sender_id="9" wall_post_id="4" message="somemesage"/>
	<wall_messages sender_id="9" wall_post_id="4" message="somemesage"/>
	<wall_messages sender_id="9" wall_post_id="4" message="somemesage"/>
	<wall_messages sender_id="9" wall_post_id="4" message="somemesage"/>
	<wall_messages sender_id="9" wall_post_id="4" message="somemesage"/>
	<wall_messages sender_id="9" wall_post_id="4" message="somemesage"/>
	<wall_messages sender_id="9" wall_post_id="4" message="somemesage"/>
	
	<chats chat_id="5"/>
	<chat_messages sender_id="10" chat_id="5" message="msg3"/>
	<chat_messages sender_id="11" chat_id="5" message="msg4"/>
	<chats_join_table user_id="10" chat_id="5"/>
	<chats_join_table user_id="11" chat_id="5"/>	
	<images image_id="1" imagePath="/testPath"/>
	<images image_id="2" imagePath="/testPath2"/>
	<images image_id="3" imagePath="/testPath3" user_id="5"/>
	<images imagePath="/testPath4" user_id="5"/>
	<likes sender_id="1" wall_post_id="3"/>
	
	
    <tasks task_id="1" assigner="username2" name="testTask1" description="test description" assignee="username1"/>
    <tasks assigner="username2" name="testTask2" description="test description" assignee="username3"/>
	<authorities username="username2" authority="ROLE_USER"/>
</dataset>
